/*

+───────────┌─────────┌─────────+
|USER_CR_ID |ASSET_ID |LAST_UPD |
+───────────└─────────└─────────+

ASSET_ID       INT      NOT NULL    AUTO_INCREMENT                          PRIMARY KEY,
USER_CR_ID     INT      NOT NULL    FOREIGN KEY REFERENCES USERS(USER_ID),
LAST_UPD       DATETIME DEFAULT     CURRENT_TIMESTAMP                       ON UPDATE CURRENT_TIMESTAMP

*/

CREATE TABLE ASSET_MGMT (
    ASSET_ID       INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_CR_ID     INT      NOT NULL,
    FOREIGN KEY (USER_CR_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;